### ISSUE TITLE
Found a scrolling bug when in chatroom

### ISSUE THREAD

**Issue by UnknownCrafts** [ChatKitty/chatkitty-example-react-native#7] opened 2021-01-14 13:47 UTC
<img width="1440" alt="Screen Shot 2021-01-14 at 8 46 18 AM" src="https://user-images.githubusercontent.com/65975222/104598846-0ade3900-5645-11eb-998d-5fdb826f5962.png">
This bug can be recreated when using a mouse scroll wheel. The bug doesn't occur with a touchpad.

btw I didn't change the CSS at all.

**Comment by aerovulpe** [comment] 2021-01-14 14:57
@FakeZombieCraft what's the exact issue? I'm not sure what's wrong from this static image. Also, what browser version are you using?

**Comment by UnknownCrafts** [comment] 2021-01-14 17:40
@aerovulpe I am using safari, the latest version(14.0.2). I can try to record a video and show you. The glitch happens when I scroll too much, it wouldn't reset the scroll either.

**Comment by UnknownCrafts** [comment] 2021-01-14 17:48
https://user-images.githubusercontent.com/65975222/104628776-a0d68b80-5666-11eb-8f49-8e6a3a10118c.mov

@aerovulpe The starting of the video is me trying to scroll using an external mouse, near the mid when the screen starts to glitch I am scrolling using a touchpad, and then near the end I am back to scrolling using an external mouse

**Comment by UnknownCrafts** [comment] 2021-01-14 17:50
I hope that this video helps in describing the situation

**Comment by aerovulpe** [comment] 2021-01-14 21:50
@FakeZombieCraft Thanks for the video and the context! Very helpful.

Looks like an issue with Gifted Chat https://github.com/FaridSafi/react-native-gifted-chat

I can't replicate it on my Windows machine using Chrome though. Is it still happening with the latest commit?

**Comment by UnknownCrafts** [comment] 2021-01-15 00:52
@aerovulpe let me check

**Comment by UnknownCrafts** [comment] 2021-01-15 01:13
@aerovulpe I checked and I am sure that I have the same versions of libraries as the latest commit, I went over to the gifted chat link and apparently, the bugs are not getting fixed quickly and the development on the library itself has gotten really slow. https://github.com/FaridSafi/react-native-gifted-chat/issues/1973 

Otherwise, the glitch could be because of safari. I hope that the chatting app will not need a library overhaul.

**Comment by UnknownCrafts** [comment] 2021-01-15 01:18
I will go test this bug on chrome

**Comment by UnknownCrafts** [comment] 2021-01-15 01:22
Huh, its a glitch with safari, chrome seems fine. That's weird. Well any ideas on how this can get fixed?

**Comment by UnknownCrafts** [comment] 2021-01-15 01:34
I think I just realized that it's this safari bouncy scroll that probably does this glitch. 

https://user-images.githubusercontent.com/65975222/104669297-ca63d700-56a7-11eb-9176-6e5cd9119229.mov

**Comment by aerovulpe** [comment] 2021-01-15 23:13
@FakeZombieCraft Yeah, I think it's a Safari bounce issue. I was able to replicate it on an old iPhone.

**Comment by aerovulpe** [comment] 2021-01-15 23:17
Also, yeah, I've noticed development on https://github.com/FaridSafi/react-native-gifted-chat has slowed down. Hopefully, it picks back up, but even if not, I plan to make this project as stable and reliable as I can. If Gifted Chat stops getting updates, I don't mind creating a fork of it and maintaining that.

**Comment by aerovulpe** [comment] 2021-01-16 19:21
Since this is a Safari issue not caused by this project. I think it's safe to close this issue.

**Closed as completed by aerovulpe** 2021-01-16 19:21 UTC
